# sops configuration file
# This file defines which keys can decrypt which secrets

# You need to add your age public key here after generating it
# Run: age-keygen -y ~/.ssh/id_ed25519 (or your SSH key path)
# Then add the output to the keys list below

keys:
  # Age public keys for each machine/user
  - &user_naroslife age1xx32wg6juew8df7a4v33fwfxz760y4wnuwrvx86xv5v2tzlptclqupz8jp

creation_rules:
  # Rule for any YAML files in secrets directory
  - path_regex: ^secrets/.*\.ya?ml$
    key_groups:
      - age:
          - *user_naroslife
        # Add more keys here as needed for additional machines:
        # - *another_machine
