{
  config,
  pkgs,
  lib,
  ...
}:
{
  programs.readline = {
    enable = true;

    # Readline bindings (for bash and other readline-using programs)
    bindings = {
      # History search with arrow keys
      "\\e[A" = "history-search-backward";
      "\\e[B" = "history-search-forward";

      # Ctrl+Arrow for word navigation
      "\\e[1;5C" = "forward-word";
      "\\e[1;5D" = "backward-word";
      "\\e[5C" = "forward-word";
      "\\e[5D" = "backward-word";
      "\\e\\e[C" = "forward-word";
      "\\e\\e[D" = "backward-word";

      # Home/End keys
      "\\e[H" = "beginning-of-line";
      "\\e[F" = "end-of-line";
      "\\e[1~" = "beginning-of-line";
      "\\e[4~" = "end-of-line";

      # Delete key
      "\\e[3~" = "delete-char";

      # Ctrl+Delete to delete word
      "\\e[3;5~" = "kill-word";

      # Tab completion
      "\\t" = "menu-complete";
      "\\e[Z" = "menu-complete-backward";

      # Clear screen with Ctrl+L
      "\\C-l" = "clear-screen";

      # Quick editing
      "\\C-w" = "backward-kill-word";
      "\\C-u" = "unix-line-discard";
    };

    # Readline variables
    variables = {
      # Basic behavior
      bell-style = "none"; # No bell
      colored-stats = true; # Color files by type in completions
      colored-completion-prefix = true; # Color the common prefix
      completion-ignore-case = true; # Case-insensitive completion
      completion-map-case = true; # Treat - and _ as equivalent
      expand-tilde = true; # Expand ~ to home directory
      mark-directories = true; # Append / to directory names
      mark-symlinked-directories = true; # Append / to symlinked directories
      show-all-if-ambiguous = true; # Show all completions immediately
      show-all-if-unmodified = true; # Show all completions if no partial completion
      visible-stats = true; # Show file type indicators

      # History
      history-preserve-point = true; # Preserve cursor position in history
      history-size = 10000; # Maximum history entries
      revert-all-at-newline = true; # Revert history edits on new line

      # Completion behavior
      menu-complete-display-prefix = true; # Show common prefix when menu completing
      skip-completed-text = true; # Insert only missing text
      completion-query-items = 200; # Ask before showing >200 completions

      # Input
      enable-keypad = true; # Enable keypad
      input-meta = true; # Enable 8-bit input
      output-meta = true; # Enable 8-bit output
      convert-meta = false; # Don't strip 8th bit

      # Editing
      enable-bracketed-paste = true; # Better paste handling

      # Vi mode settings (if you prefer vi mode)
      # editing-mode = "vi";
      # show-mode-in-prompt = true;
      # vi-ins-mode-string = "\\1\\e[6 q\\2";  # Bar cursor for insert
      # vi-cmd-mode-string = "\\1\\e[2 q\\2";  # Block cursor for command
    };

    # Extra configuration
    extraConfig = ''
      # Custom completions
      set completion-prefix-display-length 3
      set completion-display-width -1

      # Bind PgUp/PgDown to search history
      "\e[5~": history-search-backward
      "\e[6~": history-search-forward

      # If there are more than 40 possible completions for a word,
      # ask the user if they want to see all of them
      set completion-query-items 40

      # Be more intelligent when autocompleting
      set skip-completed-text on

      # Custom color settings for LS_COLORS
      set colored-completion-prefix on
      set colored-stats on
    '';
  };

  # Also create .inputrc for programs that don't use programs.readline
  home.file.".inputrc" = {
    text = ''
      # This file is generated by home-manager
      # See modules/shells/readline.nix for configuration

      # Include system-wide inputrc if it exists
      $include /etc/inputrc

      ${config.programs.readline.extraConfig}
    '';
  };
}
